apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- "../../base"

commonLabels:
  redis.failover.io/tenant: ports
  redis.failover.io/product: testing

nameSuffix: "-ports"

namespace: ports
patches:
- port.yaml
- resources.yaml

patchesJson6902:
  - target:
      group: databases.spotahome.com
      version: v1
      kind: RedisFailover
      name: redis
    patch: |-
      - op: replace
        path: /spec/redis/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/0/labelSelector/matchLabels/redis.failover.io~1tenant
        value: ports
      - op: replace
        path: /spec/sentinel/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/0/labelSelector/matchLabels/redis.failover.io~1tenant
        value: ports
